In [29]:
import numpy as np

In [30]:
list5=[1,2,3,4]
np.array(list5)

array([1, 2, 3, 4])

In [31]:
list1=[1,1,2,3,3,4]

In [32]:
np.array(list1)

array([1, 1, 2, 3, 3, 4])

In [33]:
list2=['a','b',1,2]

In [34]:
arr=np.array(list2)

In [35]:
type(arr)

numpy.ndarray

In [36]:
arr.shape

(4,)

In [37]:
arr1= np.array([[1,2,3],[4,5,6]])


In [38]:
#2 dimensions
arr1.shape

(2, 3)

In [39]:
arr2= np.array([[1,2],[3,4],[5,6]])

In [40]:
arr2.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [41]:
arr2.shape


(3, 2)

In [42]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [43]:
type(np.array((1,2,3,4)))

numpy.ndarray

In [44]:
dict ={'a':1,'b':2,'c':3,'d':4}

Value = list(dict.values())

In [45]:
Array = np.array(Value)
Array

array([1, 2, 3, 4])

In [46]:
A=Array.reshape(2,2)
A

array([[1, 2],
       [3, 4]])

In [47]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a=np.arange(1,10,2)

In [49]:
a

array([1, 3, 5, 7, 9])

In [50]:
a.reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [51]:
a.shape

(5,)

In [52]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [53]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [54]:
np.arrange

AttributeError: module 'numpy' has no attribute 'arrange'

In [ ]:
np.linspace(1,20,40)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#3 dim array

np.ones((5,2,8))

#2,8 represent the inner array 2 rows and 8 colmns 
# 5 represent the outer array 

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [ ]:
5 + np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.eye(6).reshape(12,3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(6).reshape(36,1)

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.]])

In [ ]:
np.eye(6).reshape(2,18)

array([[1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 1.]])

In [ ]:
print("Random Number generation")
np.random.rand(2,3)

Random Number generation


array([[0.15430103, 0.47496815, 0.23471622],
       [0.54335155, 0.29713998, 0.98235526]])

In [ ]:
print("Random number following a normal distribution with mean=0 and std=1")
np.random.randn(5,3)

Random number following a normal distribution with mean=0 and std=1


array([[ 1.00092491, -1.77510811,  1.54837204],
       [ 1.32895342,  0.02814451, -0.14054091],
       [-0.42388959, -0.45592553,  0.52614986],
       [-0.50593607,  0.94892736,  1.48993554],
       [ 0.34280552,  1.13395141, -0.40274865]])

In [ ]:
np.random.randint(1,100,10)

array([ 6, 77, 38, 22, 33, 83,  2, 90, 93, 31])

In [ ]:
np.random.randint(1,100,(4,4))

array([[ 5,  6, 48, 89],
       [15, 90,  1, 61],
       [27, 62, 88,  5],
       [68, 53, 90, 31]])

In [ ]:
B=np.arange(0,11)
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
B[2:11]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
B[2:7]

array([2, 3, 4, 5, 6])

In [ ]:
B[-1:7:-1]

array([10,  9,  8])

In [55]:
C=np.random.randint(2,100,20).reshape(5,4)
C

array([[23, 19, 18, 61],
       [ 6, 60, 37, 27],
       [13, 56,  5, 95],
       [88, 32, 61, 77],
       [61, 68, 25, 16]])

In [56]:
C[0:3,0:3]

array([[23, 19, 18],
       [ 6, 60, 37],
       [13, 56,  5]])

In [57]:
C[4: ,1:4]

array([[68, 25, 16]])

In [58]:
C[1:4,1:2]

array([[60],
       [56],
       [32]])

In [ ]:
C[3: ,1:4]

array([[52, 53, 99],
       [96, 29, 67]])

In [59]:
C[2:4,1:3]

array([[56,  5],
       [32, 61]])

In [60]:
C[-3:-1,-3:-1]

array([[56,  5],
       [32, 61]])

In [64]:
C[2:4]

array([[13, 56,  5, 95],
       [88, 32, 61, 77]])

In [73]:
C[2:4,0:1]

array([[13],
       [88]])

In [74]:
C[2:4,3:]

array([[95],
       [77]])

In [84]:
C[2:4,0:4:3]

array([[13, 95],
       [88, 77]])

In [85]:
D= np.random.randint(1,100,(3,3))
E= np.random.randint(20,100,(3,3))

In [86]:
D

array([[40, 57, 92],
       [54, 68, 99],
       [44,  2, 92]])

In [87]:
E

array([[56, 94, 67],
       [21, 53, 98],
       [27, 52, 80]])

In [88]:
D + E

array([[ 96, 151, 159],
       [ 75, 121, 197],
       [ 71,  54, 172]])

In [89]:
D - E

array([[-16, -37,  25],
       [ 33,  15,   1],
       [ 17, -50,  12]])

In [90]:
D * E

array([[2240, 5358, 6164],
       [1134, 3604, 9702],
       [1188,  104, 7360]])

In [91]:
D / E

array([[0.71428571, 0.60638298, 1.37313433],
       [2.57142857, 1.28301887, 1.01020408],
       [1.62962963, 0.03846154, 1.15      ]])

In [92]:
D % E

array([[40, 57, 25],
       [12, 15,  1],
       [17,  2, 12]])

In [93]:
np.sqrt(D)

array([[6.32455532, 7.54983444, 9.59166305],
       [7.34846923, 8.24621125, 9.94987437],
       [6.63324958, 1.41421356, 9.59166305]])

In [94]:
np.exp(D)

array([[2.35385267e+17, 5.68572000e+24, 9.01762841e+39],
       [2.83075330e+23, 3.40427605e+29, 9.88903032e+42],
       [1.28516001e+19, 7.38905610e+00, 9.01762841e+39]])

In [95]:
np.log10(D)

array([[1.60205999, 1.75587486, 1.96378783],
       [1.73239376, 1.83250891, 1.99563519],
       [1.64345268, 0.30103   , 1.96378783]])

In [96]:
F= np.arange(1,10)

In [97]:
F

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
F[2:]=1000 #broadcasting


In [101]:
F

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [103]:
np.dot(D,E)

array([[ 5921, 11565, 15626],
       [ 7125, 13828, 18202],
       [ 4990,  9026, 10504]])

In [104]:
np.matmul(D,E)

array([[ 5921, 11565, 15626],
       [ 7125, 13828, 18202],
       [ 4990,  9026, 10504]])