In [1]:
import pandas as pd


In [2]:
import numpy as np

In [5]:
#create a dataframe

np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [11]:

df=pd.DataFrame(data=np.arange(0,20).reshape(5,4) ,index=['Row1','Row2','Row3','Row4','Row5'],columns=['Coloumn1','Coloumn2','Coloumn3','Coloumn4'])
df

Coloumn1  Coloumn2  Coloumn3  Coloumn4
Row1         0         1         2         3
Row2         4         5         6         7
Row3         8         9        10        11
Row4        12        13        14        15
Row5        16        17        18        19

In [12]:
type(df)

pandas.core.frame.DataFrame

In [20]:
df.head(2)

Coloumn1  Coloumn2  Coloumn3  Coloumn4
Row1         0         1         2         3
Row2         4         5         6         7

In [19]:
df.tail(2)

Coloumn1  Coloumn2  Coloumn3  Coloumn4
Row4        12        13        14        15
Row5        16        17        18        19

In [21]:
df.describe()

Coloumn1   Coloumn2   Coloumn3   Coloumn4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [24]:
df[['Coloumn1','Coloumn2','Coloumn3']]

Coloumn1  Coloumn2  Coloumn3
Row1         0         1         2
Row2         4         5         6
Row3         8         9        10
Row4        12        13        14
Row5        16        17        18

In [25]:
df[['Coloumn1']]

Coloumn1
Row1         0
Row2         4
Row3         8
Row4        12
Row5        16

In [26]:
type(df[['Coloumn1']])

pandas.core.frame.DataFrame

In [27]:
df['Coloumn1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Coloumn1, dtype: int32

In [28]:
type(df['Coloumn1'])

pandas.core.series.Series

In [30]:
df.loc[['Row1','Row3']]



Coloumn1  Coloumn2  Coloumn3  Coloumn4
Row1         0         1         2         3
Row3         8         9        10        11

In [31]:
df.iloc[0:4]

Coloumn1  Coloumn2  Coloumn3  Coloumn4
Row1         0         1         2         3
Row2         4         5         6         7
Row3         8         9        10        11
Row4        12        13        14        15

In [32]:
df.iloc[0:3,0:2]

Coloumn1  Coloumn2
Row1         0         1
Row2         4         5
Row3         8         9

In [34]:
df.iloc[0:3, 0:2]

Coloumn1  Coloumn2
Row1         0         1
Row2         4         5
Row3         8         9

In [35]:
df.iloc[2:4,1:3]

Coloumn2  Coloumn3
Row3         9        10
Row4        13        14

In [36]:
df.iloc[2:4,1:3].values

array([[ 9, 10],
       [13, 14]])

In [37]:
np.nan

nan

In [41]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4],[5,4,3]],index=["Row1","Row2","Row3"],columns=["Column1","Column2","Column3"])
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4
Row3        5      4.0        3

In [42]:
df.isnull()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False
Row3    False    False    False

In [43]:
df.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [44]:
df.isna()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False
Row3    False    False    False

In [45]:

df.isna().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [46]:
df


Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4
Row3        5      4.0        3

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Row1 to Row3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Column1  3 non-null      int64  
 1   Column2  2 non-null      float64
 2   Column3  3 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 96.0+ bytes


In [48]:
df.head()

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4
Row3        5      4.0        3

In [51]:
df['Column1'].value_counts()

1    2
5    1
Name: Column1, dtype: int64

In [52]:
df['Column1'].unique()

array([1, 5], dtype=int64)

In [53]:
df['Column1'].nunique()

2

In [84]:
df1 = pd.DataFrame({'A':[1,2,3],'B':[1,1,1]})
df1

A  B
0  1  1
1  2  1
2  3  1

In [57]:
df1['A'].unique()


array([1, 2, 3], dtype=int64)

In [58]:
df1['B'].unique()

array([1], dtype=int64)

In [59]:
df1['A'].nunique()

3

In [60]:
df1['B'].nunique()

1

In [62]:
df1.nunique()

A    3
B    1
dtype: int64

In [65]:
df1.nunique(axis=0)

A    3
B    1
dtype: int64

In [66]:
df1.nunique(axis=1)

0    1
1    2
2    2
dtype: int64

In [67]:
df1['A']>2

0    False
1    False
2     True
Name: A, dtype: bool

In [68]:
df1[df1['A']>2]

A  B
2  3  1

In [80]:
df1.to_csv('test.csv',index=False)

In [81]:
df1 =pd.read_csv('test.csv')
df1

A  B
0  1  1
1  2  1
2  3  1

In [85]:
df1.to_excel('test.xlsx',index=False)

In [86]:
df1=pd.read_excel('test.xlsx')
df1

A  B
0  1  1
1  2  1
2  3  1

In [87]:
pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item',sep='\t')

HTTPError: HTTP Error 403: Forbidden

In [89]:
data = '{"employee_name":"Anna","email":"annaelsaluiz@gmail.com","job_profile":[{"title":"Team Lead","role":"developer"}]}'

In [90]:
type(data)

str

In [92]:
df2=pd.read_json(data)
df2

employee_name                   email  \
0          Anna  annaelsaluiz@gmail.com   

                                   job_profile  
0  {'title': 'Team Lead', 'role': 'developer'}

In [94]:
df2['salary']=100000
df2

employee_name                   email  \
0          Anna  annaelsaluiz@gmail.com   

                                   job_profile  salary  
0  {'title': 'Team Lead', 'role': 'developer'}  100000

In [95]:
df2['job_profile']

0    {'title': 'Team Lead', 'role': 'developer'}
Name: job_profile, dtype: object

In [96]:
pd.read_json(data,orient='records')

employee_name                   email  \
0          Anna  annaelsaluiz@gmail.com   

                                   job_profile  
0  {'title': 'Team Lead', 'role': 'developer'}

In [97]:
pd.read_json(data,orient='index')

0
employee_name                                           Anna
email                                 annaelsaluiz@gmail.com
job_profile    [{'title': 'Team Lead', 'role': 'developer'}]

In [98]:
pd.read_json(data,orient='columns')

employee_name                   email  \
0          Anna  annaelsaluiz@gmail.com   

                                   job_profile  
0  {'title': 'Team Lead', 'role': 'developer'}

In [101]:
import pandas as pd 
df3=pd.DataFrame([['a','b'],['c','d']],
                index=['row 1','row 2'],
                columns=['col 1','col 2'])
df3                

col 1 col 2
row 1     a     b
row 2     c     d

In [103]:
df3.to_csv('file1.csv')

In [105]:
df3.to_excel('file1.xlsx')

In [108]:
df3.to_json(orient='index')

'{"row 1":{"col 1":"a","col 2":"b"},"row 2":{"col 1":"c","col 2":"d"}}'

In [114]:
df4= pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)
df4

0      1     2     3     4    5     6     7     8     9      10    11  \
0     1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04   
1     1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
2     1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
3     1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

       12    13  
0    3.92  1065  
1    3.40  1050  
2    3.17  1185  
3    3.45  1480  
4    2.93   735  
..    ...   ...  
173  1.74   740  
174  1.56   750  
175  1.56   835  
176  1.62   840  
177  1.60   560  

[178 rows x 14 columns]

In [115]:
df4.head(10)

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   
5   1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97  6.75  1.05  2.85   
6   1  14.39  1.87  2.45  14.6   96  2.50  2.52  0.30  1.98  5.25  1.02  3.58   
7   1  14.06  2.15  2.61  17.6  121  2.60  2.51  0.31  1.25  5.05  1.06  3.58   
8   1  14.83  1.64  2.17  14.0   97  2.80  2.98  0.29  1.98  5.20  1.08  2.85   
9   1  13.86  1.35  2.27  16.0   98  2.98  3.15  0.22  1.85  7.22  1.01  3.55   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735  
5  1450  
6  1290  
7  1295  
8  1045  
9  1045

In [116]:
df4.tail(10)

0      1     2     3     4    5     6     7     8     9          10  \
168   3  13.58  2.58  2.69  24.5  105  1.55  0.84  0.39  1.54   8.660000   
169   3  13.40  4.60  2.86  25.0  112  1.98  0.96  0.27  1.11   8.500000   
170   3  12.20  3.03  2.32  19.0   96  1.25  0.49  0.40  0.73   5.500000   
171   3  12.77  2.39  2.28  19.5   86  1.39  0.51  0.48  0.64   9.899999   
172   3  14.16  2.51  2.48  20.0   91  1.68  0.70  0.44  1.24   9.700000   
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.700000   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.300000   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.200000   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.300000   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.200000   

       11    12   13  
168  0.74  1.80  750  
169  0.67  1.92  630  
170  0.66  1.83  510  
171  0.57  1.63  470  
172  0.62  1.71  660  
173  0.64  1.74  740  
174  0.70  1.56  750  
175  0.59  1.56  835  
176  0.60  1.62  840  
177  0.61  1.60  560

In [117]:
df4.describe()

0           1           2           3           4           5   \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean     1.938202   13.000618    2.336348    2.366517   19.494944   99.741573   
std      0.775035    0.811827    1.117146    0.274344    3.339564   14.282484   
min      1.000000   11.030000    0.740000    1.360000   10.600000   70.000000   
25%      1.000000   12.362500    1.602500    2.210000   17.200000   88.000000   
50%      2.000000   13.050000    1.865000    2.360000   19.500000   98.000000   
75%      3.000000   13.677500    3.082500    2.557500   21.500000  107.000000   
max      3.000000   14.830000    5.800000    3.230000   30.000000  162.000000   

               6           7           8           9           10          11  \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean     2.295112    2.029270    0.361854    1.590899    5.058090    0.957449   
std      0.625851    0.998859    0.124453    0.572359    2.318286    0.228572   
min      0.980000    0.340000    0.130000    0.410000    1.280000    0.480000   
25%      1.742500    1.205000    0.270000    1.250000    3.220000    0.782500   
50%      2.355000    2.135000    0.340000    1.555000    4.690000    0.965000   
75%      2.800000    2.875000    0.437500    1.950000    6.200000    1.120000   
max      3.880000    5.080000    0.660000    3.580000   13.000000    1.710000   

               12           13  
count  178.000000   178.000000  
mean     2.611685   746.893258  
std      0.709990   314.907474  
min      1.270000   278.000000  
25%      1.937500   500.500000  
50%      2.780000   673.500000  
75%      3.170000   985.000000  
max      4.000000  1680.000000